server: "mudassars:bzxOaqKQcMslHb9gCJbNUXm7vDJn6WAbainToGdJlwiaEWKwEy@beta-hub.lambdatest.com"

common_caps:
  "projectName": "LT"
  "build": "lambdatest-build"
  "isRealMobile": true
  "platform" : "Android"
  "app" : "lt://APP10020521646306620332595"

browser_caps:
  -
    "deviceName": "Galaxy S21"
    "platformVersion": "11"
    "name": "parallel_test_1"
  -
    "deviceName": "Google Pixel 6"
    "platformVersion": "12"
    "name": "parallel_test_2"
