server: "beta-hub.lambdatest.com/wd/hub"

common_caps:
  "projectName": "LT"
  "build": "lambdatest-build"
  "isRealMobile": true
  "platformName" : "Android"
  "app" : "lt://APP10020521646306620332595"

browser_caps:
  -
    "deviceName": "Google Pixel 3"
    "platformVersion": "10"
    "name": "parallel_test_1"
  -
    "deviceName": "Galaxy A12"
    "platformVersion": "10"
    "name": "parallel_test_2"
